"""Turn simulated users into real HTTP load, and log every request as it happens.

This is the piece that replaces "traffic generated by the cache itself". It issues genuine
concurrent requests against the running applications, which do genuine work — a real
ranking computation, a real SQL query — and report their measured cost to AURA.

Three things it does that a naive load generator does not:

**Open-loop arrivals with a bounded worker pool.** Requests are scheduled by the clock, not
by when the previous one finished. If the system slows down, work piles up and the queue
grows, which is exactly how real latency happens and the only way a flash crowd means
anything. A closed-loop generator with N threads silently throttles itself the moment the
backend struggles, and then reports that everything is fine.

**Late requests are counted, not hidden.** If an arrival cannot be dispatched on time, the
delay is recorded as part of that request's latency. This is coordinated omission, and
ignoring it is the most common way load tests report a p99 that is off by an order of
magnitude.

**Everything is logged as it happens.** One JSON line per request, streamed to disk and
optionally to a live consumer, so the dashboard can show the request path rather than an
aggregate that arrives thirty seconds later.

Run it::

    python -m simulator.driver --users 40000 --rps 300 --duration 120
    python -m simulator.driver --rps 300 --duration 300 --scenario flash_crowd
"""

from __future__ import annotations

import argparse
import asyncio
import contextlib
import json
import logging
import os
import random
import sys
import time
from collections import Counter, deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import httpx

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from simulator.population import Action, Event, Population, SessionEngine, summarise  # noqa: E402

LOG = logging.getLogger("aura.simulator")

DEFAULT_ENDPOINTS = {
    "recommendation": "http://localhost:8101",
    "analytics": "http://localhost:8102",
    "content": "http://localhost:8103",
}

#: Which service serves each action, and the path template it uses.
ROUTES: dict[Action, tuple[str, str]] = {
    Action.HOME: ("recommendation", "/work/{user}"),
    Action.CLICK: ("recommendation", "/work/{user}"),
    Action.VIEW: ("content", "/work/{item}"),
    Action.SEARCH: ("content", "/work/{query}"),
    Action.CART: ("content", "/work/{item}"),
    Action.PURCHASE: ("analytics", "/work/{user}"),
    Action.DASHBOARD: ("analytics", "/work/{region}"),
}


@dataclass
class RequestRecord:
    """One completed request. Serialised as a single JSON line."""

    t: float
    seq: int
    action: str
    service: str
    user_id: int
    epoch: int
    segment: str
    status: int
    #: Time from *scheduled* arrival to response, including any dispatch delay.
    latency_ms: float
    #: Time the request actually spent in flight.
    service_ms: float
    #: How late the dispatcher was. Non-zero means the generator itself is saturated.
    dispatch_delay_ms: float
    cache: str = "unknown"
    bypass: bool = False
    error: str = ""

    def as_line(self) -> str:
        return json.dumps(self.__dict__, separators=(",", ":"))


@dataclass
class Metrics:
    """Windowed and cumulative counters. Windowed is what makes adaptation visible."""

    started: float = field(default_factory=time.monotonic)
    sent: int = 0
    completed: int = 0
    errors: int = 0
    late_dispatches: int = 0
    by_action: Counter[str] = field(default_factory=Counter)
    by_cache: Counter[str] = field(default_factory=Counter)
    latencies: deque[float] = field(default_factory=lambda: deque(maxlen=20_000))
    window: deque[tuple[float, float, str]] = field(default_factory=lambda: deque(maxlen=50_000))

    def record(self, rec: RequestRecord) -> None:
        self.completed += 1
        self.by_action[rec.action] += 1
        self.by_cache[rec.cache] += 1
        if rec.error:
            self.errors += 1
        if rec.dispatch_delay_ms > 50.0:
            self.late_dispatches += 1
        self.latencies.append(rec.latency_ms)
        self.window.append((time.monotonic(), rec.latency_ms, rec.cache))

    def quantile(self, q: float) -> float:
        if not self.latencies:
            return 0.0
        ordered = sorted(self.latencies)
        idx = min(len(ordered) - 1, int(len(ordered) * q))
        return ordered[idx]

    def window_view(self, seconds: float = 10.0) -> dict[str, Any]:
        """Metrics over the last few seconds only.

        Cumulative averages over a long run hide exactly the thing this project claims:
        a policy that adapts after thirty seconds looks identical to one that never did.
        """
        cutoff = time.monotonic() - seconds
        recent = [(t, lat, cache) for t, lat, cache in self.window if t >= cutoff]
        if not recent:
            return {"rps": 0.0, "p50_ms": 0.0, "p95_ms": 0.0, "hit_rate": 0.0, "n": 0}
        lats = sorted(lat for _, lat, _ in recent)
        hits = sum(1 for _, _, c in recent if c in ("l1", "l2"))
        return {
            "rps": round(len(recent) / seconds, 1),
            "p50_ms": round(lats[len(lats) // 2], 1),
            "p95_ms": round(lats[min(len(lats) - 1, int(len(lats) * 0.95))], 1),
            "hit_rate": round(hits / len(recent), 3),
            "n": len(recent),
        }

    def summary(self) -> dict[str, Any]:
        elapsed = max(time.monotonic() - self.started, 1e-9)
        return {
            "sent": self.sent,
            "completed": self.completed,
            "errors": self.errors,
            "late_dispatches": self.late_dispatches,
            "elapsed_s": round(elapsed, 1),
            "rps": round(self.completed / elapsed, 1),
            "p50_ms": round(self.quantile(0.50), 1),
            "p95_ms": round(self.quantile(0.95), 1),
            "p99_ms": round(self.quantile(0.99), 1),
            "by_action": dict(self.by_action),
            "by_cache": dict(self.by_cache),
        }


class EventLog:
    """Streams one JSON line per request, flushed continuously.

    Buffered writes would be faster, but a log that only appears when the process exits is
    useless for watching a run, and watching the run is the point.
    """

    def __init__(self, path: Path | None) -> None:
        self.path = path
        self._fh = None
        if path is not None:
            path.parent.mkdir(parents=True, exist_ok=True)
            self._fh = path.open("w", encoding="utf-8")

    def write(self, rec: RequestRecord) -> None:
        if self._fh is None:
            return
        self._fh.write(rec.as_line() + "\n")
        self._fh.flush()

    def close(self) -> None:
        if self._fh is not None:
            self._fh.close()


class Driver:
    def __init__(
        self,
        endpoints: dict[str, str],
        *,
        concurrency: int = 256,
        timeout_s: float = 30.0,
        log: EventLog | None = None,
    ) -> None:
        limits = httpx.Limits(max_connections=concurrency, max_keepalive_connections=concurrency)
        self.client = httpx.AsyncClient(timeout=timeout_s, limits=limits)
        self.endpoints = endpoints
        self.metrics = Metrics()
        self.log = log or EventLog(None)
        self._sem = asyncio.Semaphore(concurrency)
        self._seq = 0
        self._first_error = ""

    async def aclose(self) -> None:
        await self.client.aclose()

    def _url(self, event: Event) -> tuple[str, str]:
        service, template = ROUTES[event.action]
        base = self.endpoints.get(service, DEFAULT_ENDPOINTS[service])
        ident = template.format(
            user=event.user_id,
            item=event.item_id if event.item_id is not None else 0,
            query=(event.query or "none").replace(" ", "-"),
            region=event.region_id,
        )
        return service, f"{base.rstrip('/')}{ident}"

    async def fire(self, event: Event, scheduled_at: float) -> None:
        """Issue one request. Never raises: a load generator that dies on a 500 is useless."""
        async with self._sem:
            dispatch_delay = max(0.0, time.monotonic() - scheduled_at)
            service, url = self._url(event)
            self._seq += 1
            seq = self._seq

            # The epoch is what makes a click invalidate by construction: after a click the
            # user's key is different, so the previous ranking is unreachable rather than
            # stale. `fresh` is the deliberate bypass that keeps the learner fed.
            params = {
                "epoch": event.epoch,
                "segment": event.segment,
                "region": event.region_id,
                "session": event.session_id,
            }
            if event.bypass_cache:
                params["fresh"] = "true"

            started = time.monotonic()
            status = 0
            cache = "unknown"
            error = ""
            try:
                resp = await self.client.get(url, params=params)
                status = resp.status_code
                cache = resp.headers.get("x-aura-cache", "unknown")
                if cache == "unknown":
                    with contextlib.suppress(Exception):
                        body = resp.json()
                        if isinstance(body, dict):
                            # `served_from` is the field the applications actually return.
                            # Looking only for `cache`/`source` meant every request was
                            # recorded as "unknown" and the hit rate read 0.0% for the whole
                            # run even when the cache was answering most of them -- a
                            # measurement bug that looked exactly like a broken cache.
                            cache = str(
                                body.get("served_from")
                                or body.get("cache")
                                or body.get("source")
                                or "unknown"
                            )
            except Exception as exc:  # noqa: BLE001
                error = f"{type(exc).__name__}: {exc}"[:160]
                if not self._first_error:
                    self._first_error = f"{url} -> {error}"
                    LOG.error(
                        "first request failure (all further ones are counted, not logged): %s",
                        self._first_error,
                    )

            finished = time.monotonic()
            rec = RequestRecord(
                t=time.time(),
                seq=seq,
                action=event.action.value,
                service=service,
                user_id=event.user_id,
                epoch=event.epoch,
                segment=event.segment,
                status=status,
                # Measured from the scheduled arrival, not from dispatch. Ignoring the
                # difference is coordinated omission and it flatters every result.
                latency_ms=(finished - scheduled_at) * 1000.0,
                service_ms=(finished - started) * 1000.0,
                dispatch_delay_ms=dispatch_delay * 1000.0,
                cache=cache,
                bypass=event.bypass_cache,
                error=error,
            )
            self.metrics.record(rec)
            self.log.write(rec)

    async def run(self, events: list[Event], speed: float = 1.0) -> None:
        """Replay `events` against the services on their own schedule."""
        if not events:
            return
        origin = time.monotonic()
        base_t = events[0].t_s
        tasks: set[asyncio.Task[None]] = set()

        for event in events:
            target = origin + (event.t_s - base_t) / max(speed, 1e-6)
            now = time.monotonic()
            if target > now:
                await asyncio.sleep(target - now)
            self.metrics.sent += 1
            task = asyncio.create_task(self.fire(event, target))
            tasks.add(task)
            task.add_done_callback(tasks.discard)

        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)


async def reporter(driver: Driver, every_s: float, stop: asyncio.Event) -> None:
    """Print a live line every few seconds so a run can be watched, not just waited on."""
    header = f"{'elapsed':>8} {'rps':>7} {'p50':>7} {'p95':>8} {'hit%':>6} {'inflight':>8} {'errors':>7}"
    print(header)
    print("-" * len(header))
    while not stop.is_set():
        with contextlib.suppress(asyncio.TimeoutError):
            await asyncio.wait_for(stop.wait(), timeout=every_s)
        w = driver.metrics.window_view(10.0)
        elapsed = time.monotonic() - driver.metrics.started
        inflight = driver.metrics.sent - driver.metrics.completed
        print(
            f"{elapsed:>7.0f}s {w['rps']:>7} {w['p50_ms']:>7} {w['p95_ms']:>8} "
            f"{w['hit_rate'] * 100:>5.1f}% {inflight:>8} {driver.metrics.errors:>7}"
        )


async def apply_scenario(name: str, pop: Population, aura_url: str, duration_s: float) -> None:
    """Introduce a disturbance partway through the run.

    Each one attacks a different assumption, and all of them are *caused* rather than
    injected into the request stream — the population changes, and the traffic follows.
    """
    if name == "none":
        return
    await asyncio.sleep(duration_s * 0.4)
    async with httpx.AsyncClient(timeout=5.0) as client:
        if name == "popularity_shift":
            moved = pop.shift_interests(0.25)
            LOG.warning("scenario: %d users moved to new categories", moved)
        elif name == "flash_crowd":
            # One item becomes overwhelmingly popular, as if it were shared widely.
            hot = random.randrange(pop.catalogue)
            pop.engage(hot, 5_000.0)
            LOG.warning("scenario: flash crowd on item %d", hot)
        elif name == "model_redeploy":
            with contextlib.suppress(Exception):
                await client.post(
                    f"{aura_url}/v1/version/bump", json={"namespace": "recommendation"}
                )
            LOG.warning("scenario: recommendation namespace retired to a new version")
        elif name == "price_change":
            with contextlib.suppress(Exception):
                await client.post(
                    f"{aura_url}/v1/invalidate",
                    json={"tags": ["row:product:1292"], "mode": "hard", "source": "simulator"},
                )
            LOG.warning("scenario: product 1292 price changed, dependants invalidated")
        else:
            LOG.warning("unknown scenario %r, continuing without one", name)


async def main_async(args: argparse.Namespace) -> int:
    logging.basicConfig(level=args.log_level.upper(), format="%(asctime)s %(levelname)-7s %(message)s")
    # httpx logs a line per request at INFO, which at 300 rps drowns out the live report.
    for noisy in ("httpx", "httpcore", "hpack"):
        logging.getLogger(noisy).setLevel(logging.WARNING)

    pop = Population(users=args.users, catalogue=args.catalogue, seed=args.seed)
    engine = SessionEngine(pop, seed=args.seed, bypass_rate=args.bypass_rate)
    LOG.info("population %s", json.dumps(pop.stats()))

    events = engine.arrivals(duration_s=args.duration, rps=args.rps)
    LOG.info("generated %s", json.dumps(summarise(events)))
    if args.dry_run:
        print(json.dumps(summarise(events), indent=2))
        return 0

    endpoints = dict(DEFAULT_ENDPOINTS)
    for pair in args.endpoint or []:
        name, _, url = pair.partition("=")
        endpoints[name] = url

    log = EventLog(Path(args.log_file) if args.log_file else None)
    driver = Driver(endpoints, concurrency=args.concurrency, log=log)

    stop = asyncio.Event()
    report = asyncio.create_task(reporter(driver, args.report_every_s, stop))
    scenario = asyncio.create_task(apply_scenario(args.scenario, pop, args.aura_url, args.duration))

    try:
        await driver.run(events, speed=args.speed)
    finally:
        stop.set()
        scenario.cancel()
        with contextlib.suppress(asyncio.CancelledError):
            await scenario
        with contextlib.suppress(asyncio.CancelledError):
            await report
        await driver.aclose()
        log.close()

    summary = driver.metrics.summary()
    print("\n" + json.dumps(summary, indent=2))

    # An open-loop generator will happily schedule traffic the targets cannot absorb, and
    # the result looks like a slow cache rather than an overloaded application. Say which
    # one it was, because the difference decides whether you tune the cache or the load.
    late = summary["late_dispatches"]
    if summary["sent"] and late > summary["sent"] * 0.25:
        served = summary["rps"]
        print(
            f"\n{late} of {summary['sent']} requests were dispatched late. The services could "
            f"not absorb the offered rate, so the latencies above are mostly queueing in this "
            f"script -- not the cache.\n"
            f"This run actually sustained about {served:.0f} req/s. Re-run with "
            f"--rps {max(1, int(served * 0.8))} for numbers that measure the cache."
        )
    if driver._first_error:
        print(f"\n{summary['errors']} request(s) failed. First: {driver._first_error}")
    if summary["by_cache"].get("unknown", 0) == summary["completed"] and summary["completed"]:
        print(
            "\nEvery response was recorded as cache-state 'unknown'. The applications did "
            "not return a served_from field, so the hit rate above is not measuring anything."
        )
    if args.log_file:
        print(f"\nper-request log: {args.log_file}")
    return 0 if driver.metrics.errors < driver.metrics.completed * 0.05 else 1


def main() -> int:
    p = argparse.ArgumentParser(description="Drive the AURA applications with simulated users")
    p.add_argument(
        "--users",
        type=int,
        default=4_000,
        help=(
            "population size, not a request rate. Keep it within what the services can warm: "
            "personalised keys mean the working set is roughly one object per active user, "
            "and a recommendation rebuild costs most of a second, so 40k users against a "
            "single-process service never fills the cache and the hit rate stays at zero"
        ),
    )
    p.add_argument("--catalogue", type=int, default=50_000)
    p.add_argument(
        "--rps",
        type=float,
        default=40.0,
        help=(
            "target requests per second. The ceiling is set by how fast the applications "
            "rebuild on a miss, not by this script: ask for more and the excess queues here "
            "and shows up as latency the cache did not cause"
        ),
    )
    p.add_argument("--duration", type=float, default=120.0, help="seconds of traffic")
    p.add_argument("--speed", type=float, default=1.0, help="replay faster than real time")
    p.add_argument("--concurrency", type=int, default=256)
    p.add_argument("--bypass-rate", type=float, default=0.04, help="fraction of requests that skip the cache on purpose")
    p.add_argument(
        "--scenario",
        default="none",
        choices=["none", "popularity_shift", "flash_crowd", "model_redeploy", "price_change"],
    )
    p.add_argument("--endpoint", action="append", help="service=url, repeatable")
    p.add_argument("--aura-url", default=os.environ.get("AURA_APPS_AURA_BASE_URL", "http://localhost:8080"))
    p.add_argument("--log-file", default="runs/requests.jsonl")
    p.add_argument("--report-every-s", type=float, default=5.0)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--dry-run", action="store_true", help="generate and summarise without sending anything")
    p.add_argument("--log-level", default="INFO")
    args = p.parse_args()

    try:
        return asyncio.run(main_async(args))
    except KeyboardInterrupt:
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
