"""A population of simulated users, and the sessions they run.

Why this exists
---------------
The weakest sentence in the demo was "this traffic is generated by the cache itself". A
trace replay cannot fix that, because a trace is a recording of decisions already made: the
keys are fixed in advance, so nothing the cache does can change what is asked for next.

Real caching problems are not like that. A user clicks an item, their recommendation key
changes, and the cache takes a miss it could not have avoided. Popularity concentrates
because people see what other people looked at. A flash crowd is a *consequence* of
something, not an instruction at request 20,000.

So this module models users, and lets the request stream be whatever those users cause.

The shape of it
---------------
- **40,000 users is a population, not a rate.** Almost all of them are asleep at any moment.
  Arrivals are Poisson at a configured rate; the population determines *who* arrives and
  how much locality there is, not how much load there is.
- **Three segments** with very different behaviour, because a uniform user model produces a
  uniform workload and every cache looks the same on it.
- **Interest drift and a trending feedback loop**, so popularity shifts emerge instead of
  being scripted.
- **Every click bumps the user's interaction epoch**, which is part of their cache key. That
  is invalidation by construction: the stale ranking is never requested again.

Nothing here talks to the network. `driver.py` turns these events into HTTP.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from enum import Enum
from typing import Iterator, Sequence

# --------------------------------------------------------------------------- users


class Segment(str, Enum):
    """Behavioural segments. The proportions matter more than the names.

    `POWER` users are 2% of the population and generate a disproportionate share of the
    traffic with tight reuse — they are what makes caching work at all. `DORMANT` users
    arrive rarely and almost never return within any useful horizon; caching their
    recommendations is close to pure loss, and a cache that cannot tell the difference
    wastes most of its memory on them.
    """

    POWER = "power"
    REGULAR = "regular"
    DORMANT = "dormant"


SEGMENT_MIX: dict[Segment, float] = {
    Segment.POWER: 0.02,
    Segment.REGULAR: 0.28,
    Segment.DORMANT: 0.70,
}

#: Mean actions per session, and the chance of returning within the hour.
SEGMENT_PROFILE: dict[Segment, tuple[float, float]] = {
    Segment.POWER: (14.0, 0.85),
    Segment.REGULAR: (5.0, 0.30),
    Segment.DORMANT: (2.0, 0.02),
}


@dataclass(slots=True)
class User:
    user_id: int
    segment: Segment
    #: Category weights. Drifts slowly, and jumps when the user engages with something new.
    interests: list[float]
    #: Incremented on every action that should change this user's recommendations. Part of
    #: the cache key, so a click makes the old key unreachable rather than stale.
    epoch: int = 0
    sessions: int = 0
    actions: int = 0
    last_seen_s: float = -1e9
    device: str = "web"
    region_id: int = 0

    def top_category(self) -> int:
        return max(range(len(self.interests)), key=lambda i: self.interests[i])


class Population:
    """The user base. Deterministic for a given seed."""

    def __init__(
        self,
        users: int = 40_000,
        categories: int = 24,
        catalogue: int = 50_000,
        regions: int = 12,
        seed: int = 42,
    ) -> None:
        self.rng = random.Random(seed)
        self.categories = categories
        self.catalogue = catalogue
        self.regions = regions
        self.users: list[User] = []

        segs = list(SEGMENT_MIX)
        weights = [SEGMENT_MIX[s] for s in segs]
        for uid in range(users):
            segment = self.rng.choices(segs, weights=weights, k=1)[0]
            # A user is interested in a few categories, not all of them, which is what
            # creates per-user locality worth caching.
            interests = [self.rng.random() ** 6 for _ in range(categories)]
            for _ in range(self.rng.randint(1, 3)):
                interests[self.rng.randrange(categories)] += self.rng.uniform(1.0, 3.0)
            total = sum(interests) or 1.0
            self.users.append(
                User(
                    user_id=uid,
                    segment=segment,
                    interests=[w / total for w in interests],
                    device=self.rng.choice(["web", "web", "web", "ios", "android"]),
                    region_id=self.rng.randrange(regions),
                )
            )

        # Item popularity is Zipf within a category. `trending` is the feedback loop: items
        # that get engagement become more likely to be shown, which is how a flash crowd
        # forms without anyone scripting one.
        self.item_category = [self.rng.randrange(categories) for _ in range(catalogue)]
        self.item_base = [1.0 / ((i % 5_000) + 1) ** 0.9 for i in range(catalogue)]
        self.trending: dict[int, float] = {}

        # Who is likely to arrive next. Power users arrive far more often than their share
        # of the population.
        self._arrival_weights = [
            {Segment.POWER: 40.0, Segment.REGULAR: 6.0, Segment.DORMANT: 1.0}[u.segment]
            for u in self.users
        ]
        self._arrival_total = sum(self._arrival_weights)

    # -- selection -------------------------------------------------------

    def pick_user(self) -> User:
        target = self.rng.random() * self._arrival_total
        # Walking the list is O(n) and this is called a few hundred times a second, so
        # sample a small window instead and take the best — statistically close enough and
        # constant time.
        best: User | None = None
        best_w = -1.0
        for _ in range(24):
            i = self.rng.randrange(len(self.users))
            w = self._arrival_weights[i] * self.rng.random()
            if w > best_w:
                best_w, best = w, self.users[i]
        assert best is not None
        _ = target
        return best

    def pick_item(self, user: User) -> int:
        """An item this user plausibly engages with, biased by interest and by trend."""
        if self.trending and self.rng.random() < 0.35:
            items = list(self.trending)
            weights = [self.trending[i] for i in items]
            return self.rng.choices(items, weights=weights, k=1)[0]
        category = self.rng.choices(range(self.categories), weights=user.interests, k=1)[0]
        # Zipf within the category: a few items take most of the attention.
        rank = int(self.catalogue * (self.rng.random() ** 3))
        return (category * 977 + rank) % self.catalogue

    def engage(self, item: int, weight: float = 1.0) -> None:
        self.trending[item] = self.trending.get(item, 0.0) + weight

    def decay_trending(self, factor: float = 0.97, keep: int = 400) -> None:
        """Interest fades. Without this, the first popular item stays popular forever."""
        for item in list(self.trending):
            self.trending[item] *= factor
            if self.trending[item] < 0.05:
                del self.trending[item]
        if len(self.trending) > keep:
            hottest = sorted(self.trending.items(), key=lambda kv: kv[1], reverse=True)[:keep]
            self.trending = dict(hottest)

    def shift_interests(self, fraction: float = 0.15) -> int:
        """Move a slice of the population onto new categories.

        This is the popularity-inversion attack, generated rather than injected: the keys
        that were hot go cold and new ones become hot, which is precisely what a frequency
        counter with a long memory gets wrong.
        """
        moved = 0
        for user in self.users:
            if self.rng.random() >= fraction:
                continue
            target = self.rng.randrange(self.categories)
            user.interests = [w * 0.35 for w in user.interests]
            user.interests[target] += 0.65
            total = sum(user.interests) or 1.0
            user.interests = [w / total for w in user.interests]
            user.epoch += 1
            moved += 1
        self.trending.clear()
        return moved

    def stats(self) -> dict[str, float | int]:
        by_segment: dict[str, int] = {}
        for u in self.users:
            by_segment[u.segment.value] = by_segment.get(u.segment.value, 0) + 1
        return {
            "users": len(self.users),
            "catalogue": self.catalogue,
            "categories": self.categories,
            "trending_items": len(self.trending),
            **{f"segment_{k}": v for k, v in by_segment.items()},
        }


# --------------------------------------------------------------------------- sessions


class Action(str, Enum):
    """What a user does. Each maps to a different request shape and a different cost."""

    HOME = "home"
    """Personalised recommendations. Expensive to build, cacheable per user-epoch."""

    VIEW = "view"
    """A product page. Cheap, shared across users, and depends on a mutable price row."""

    SEARCH = "search"
    """A query. Shared across users, moderately expensive, high key cardinality."""

    CLICK = "click"
    """Engagement. Bumps the user's epoch, so their next HOME key is different."""

    CART = "cart"
    PURCHASE = "purchase"
    """A write. Inserts an order, which invalidates analytics rollups."""

    DASHBOARD = "dashboard"
    """An operator looking at analytics. Rare, expensive, bursty on the hour."""


@dataclass(slots=True)
class Event:
    """One thing a user did, ready to become an HTTP request."""

    t_s: float
    user_id: int
    action: Action
    item_id: int | None = None
    query: str | None = None
    epoch: int = 0
    segment: str = "regular"
    region_id: int = 0
    device: str = "web"
    session_id: int = 0
    #: Set on events that must not be served from cache, so the learner keeps getting
    #: fresh impressions and we retain a control group.
    bypass_cache: bool = False

    def key_parts(self) -> dict[str, str]:
        return {
            "user": str(self.user_id),
            "epoch": str(self.epoch),
            "item": str(self.item_id) if self.item_id is not None else "",
        }


#: Transition table. Rows are the current action, columns the next one.
#: Tuned so that HOME is common (it is the expensive, cacheable object), CLICK follows VIEW
#: often enough to keep epochs moving, and PURCHASE is rare but not negligible.
TRANSITIONS: dict[Action, Sequence[tuple[Action, float]]] = {
    Action.HOME: ((Action.VIEW, 0.55), (Action.SEARCH, 0.25), (Action.HOME, 0.10), (Action.CLICK, 0.10)),
    Action.VIEW: ((Action.CLICK, 0.35), (Action.VIEW, 0.25), (Action.HOME, 0.20), (Action.CART, 0.12), (Action.SEARCH, 0.08)),
    Action.SEARCH: ((Action.VIEW, 0.65), (Action.SEARCH, 0.20), (Action.HOME, 0.15)),
    Action.CLICK: ((Action.VIEW, 0.45), (Action.HOME, 0.35), (Action.CART, 0.20)),
    Action.CART: ((Action.PURCHASE, 0.35), (Action.VIEW, 0.40), (Action.HOME, 0.25)),
    Action.PURCHASE: ((Action.HOME, 0.70), (Action.VIEW, 0.30)),
    Action.DASHBOARD: ((Action.DASHBOARD, 0.60), (Action.HOME, 0.40)),
}

SEARCH_TERMS = [
    "wireless earbuds", "running shoes", "office chair", "cotton shirt", "steel bottle",
    "yoga mat", "phone case", "table lamp", "coffee beans", "backpack", "keyboard",
    "monitor stand", "rain jacket", "sunglasses", "notebook", "sneakers", "watch strap",
]


class SessionEngine:
    """Turns the population into a stream of events on a virtual clock."""

    def __init__(
        self,
        population: Population,
        *,
        seed: int = 42,
        bypass_rate: float = 0.04,
        dashboard_rate: float = 0.02,
    ) -> None:
        self.pop = population
        self.rng = random.Random(seed ^ 0x5EED)
        self.bypass_rate = bypass_rate
        self.dashboard_rate = dashboard_rate
        self.session_counter = 0
        self.events_emitted = 0
        self.epoch_bumps = 0
        self.purchases = 0

    def _next_action(self, current: Action) -> Action:
        choices = TRANSITIONS[current]
        return self.rng.choices([a for a, _ in choices], weights=[w for _, w in choices], k=1)[0]

    def session(self, user: User, start_s: float) -> Iterator[Event]:
        """One user session. Yields events with increasing timestamps."""
        self.session_counter += 1
        session_id = self.session_counter
        user.sessions += 1

        mean_actions, _ = SEGMENT_PROFILE[user.segment]
        # Geometric length: most sessions are short, a few are very long.
        length = max(1, int(self.rng.expovariate(1.0 / mean_actions)))

        t = start_s
        action = Action.DASHBOARD if self.rng.random() < self.dashboard_rate else Action.HOME

        for _ in range(length):
            item: int | None = None
            query: str | None = None

            if action in (Action.VIEW, Action.CLICK, Action.CART, Action.PURCHASE):
                item = self.pop.pick_item(user)
            elif action is Action.SEARCH:
                query = self.rng.choice(SEARCH_TERMS)

            if action is Action.CLICK and item is not None:
                # Engagement moves the user and the crowd at the same time.
                self.pop.engage(item, 1.0)
                category = self.pop.item_category[item]
                user.interests[category] = min(1.0, user.interests[category] + 0.05)
                user.epoch += 1
                self.epoch_bumps += 1
            elif action is Action.PURCHASE and item is not None:
                self.pop.engage(item, 3.0)
                user.epoch += 1
                self.epoch_bumps += 1
                self.purchases += 1

            user.actions += 1
            user.last_seen_s = t
            self.events_emitted += 1

            yield Event(
                t_s=t,
                user_id=user.user_id,
                action=action,
                item_id=item,
                query=query,
                epoch=user.epoch,
                segment=user.segment.value,
                region_id=user.region_id,
                device=user.device,
                session_id=session_id,
                bypass_cache=self.rng.random() < self.bypass_rate,
            )

            # Think time. Power users are faster, and the tail is long.
            base = {Segment.POWER: 1.6, Segment.REGULAR: 3.2, Segment.DORMANT: 6.0}[user.segment]
            t += self.rng.expovariate(1.0 / base)
            action = self._next_action(action)

    def arrivals(
        self,
        duration_s: float,
        rps: float,
        start_s: float = 0.0,
        warmup_s: float | None = None,
    ) -> list[Event]:
        """Generate every event inside a window, sorted by time.

        Arrivals are Poisson rather than evenly spaced. That distinction matters: a uniform
        arrival process cannot produce the short bursts that fill a queue, and a queue that
        never fills is a cache benchmark with the interesting part removed.

        Two details keep the measured rate honest. Sessions begin *before* the window opens
        (``warmup_s``), so the window observes a system already in flight rather than one
        starting from nothing; and events are clipped to the window, because a session that
        began at second 59 of a 60-second window does not get to contribute its next four
        minutes of activity to that window's rate.
        """
        mean_events = self.mean_events_per_session()
        session_rate = max(rps / max(mean_events, 1.0), 0.01)

        # Long enough for a typical session to have finished by the time the window opens.
        if warmup_s is None:
            warmup_s = min(120.0, 6.0 * mean_events)

        window_start = start_s
        window_end = start_s + duration_s

        events: list[Event] = []
        t = start_s - warmup_s
        while t < window_end:
            t += self.rng.expovariate(session_rate)
            if t >= window_end:
                break
            user = self.pop.pick_user()
            for event in self.session(user, t):
                if event.t_s >= window_end:
                    break
                if event.t_s >= window_start:
                    events.append(event)
            if self.rng.random() < 0.05:
                self.pop.decay_trending()

        events.sort(key=lambda e: e.t_s)
        return events

    def mean_events_per_session(self) -> float:
        """Expected events per session, weighted by how often each segment arrives.

        Used to convert a target event rate into a session arrival rate. Power users arrive
        far more often than their share of the population and run much longer sessions, so
        weighting by population alone would underestimate this badly.
        """
        arrival_weight = {Segment.POWER: 40.0, Segment.REGULAR: 6.0, Segment.DORMANT: 1.0}
        weighted = 0.0
        total = 0.0
        for segment, share in SEGMENT_MIX.items():
            w = share * arrival_weight[segment]
            # `max(1, int(expovariate(1/mean)))` has a slightly higher mean than `mean`;
            # the correction keeps the generated rate close to the requested one.
            mean_actions = SEGMENT_PROFILE[segment][0]
            weighted += w * (mean_actions + 0.5)
            total += w
        return weighted / total if total else 1.0

    def stats(self) -> dict[str, float | int]:
        return {
            "sessions": self.session_counter,
            "events": self.events_emitted,
            "epoch_bumps": self.epoch_bumps,
            "purchases": self.purchases,
        }


def summarise(events: Sequence[Event]) -> dict[str, float | int]:
    """Shape of a generated stream. Used in tests and printed by the driver."""
    if not events:
        return {}
    by_action: dict[str, int] = {}
    for e in events:
        by_action[e.action.value] = by_action.get(e.action.value, 0) + 1
    span = max(events[-1].t_s - events[0].t_s, 1e-9)
    users = {e.user_id for e in events}
    keys = {(e.user_id, e.epoch) for e in events if e.action is Action.HOME}
    gaps = [events[i + 1].t_s - events[i].t_s for i in range(len(events) - 1)]
    mean_gap = sum(gaps) / len(gaps) if gaps else 0.0
    var = sum((g - mean_gap) ** 2 for g in gaps) / len(gaps) if gaps else 0.0
    return {
        "events": len(events),
        "span_s": round(span, 2),
        "rps": round(len(events) / span, 2),
        "unique_users": len(users),
        "unique_home_keys": len(keys),
        "burstiness": round(math.sqrt(var) / mean_gap, 3) if mean_gap else 0.0,
        **{f"action_{k}": v for k, v in sorted(by_action.items())},
    }


__all__ = [
    "Action",
    "Event",
    "Population",
    "Segment",
    "SessionEngine",
    "User",
    "summarise",
]
